### ISSUE TITLE
The packer-elasticsearch project referenced in the README is not publicly accessible

### ISSUE THREAD

**Issue by divideby0** [nadnerb/terraform-elasticsearch#1]
For audit and forking purposes, it'd be super useful to have access to the `packer-elasticsearch` project referenced in the README. However, both [nadnerb/packer-elasticsearch](/nadnerb/packer-elasticsearch) and [nadnerb/packer-elastic-search](/nadnerb/packer-elastic-search) return 404s. Is it accidentally configured as a private project perhaps?

**Comment by nadnerb** [comment]
Hey, thanks for the heads up. I think I transferred those projects to a company I was working for when I left. They have since made them private. I will see if I can find a local copy and push them back onto github

**Comment by nadnerb** [comment]
I have pushed the old repo.
